// src/features/links/components/NewLinkModal.jsx
import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Plus, Trash2, Mail, User, ListTree,
  Link as LinkIcon,
  CalendarDays,
} from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { useTheme } from '@/shared/context/ThemeContext'
import useMediaQuery from '@/shared/hooks/useMediaQuery'
import { Button, Input, Modal, SegmentControl, DatePickerModal, SectionLabel } from '@/shared/ui'

export default function NewLinkModal({ onClose, link = null }) {
  const { isDarkMode } = useTheme()
  const { t } = useTranslation()
  const isDesktop = useMediaQuery('(min-width: 640px)')
  const isEditing = !!link

  const buildInitialItems = () => {
    if (!link) return [{ id: 1, desc: '', amount: '' }]
    const count = link.items || 1
    return Array.from({ length: count }, (_, i) => ({
      id: i + 1,
      desc: i === 0 ? (link.client || '') : '',
      amount: i === 0 ? (link.amount?.replace(/,/g, '') || '') : '',
    }))
  }

  const [items, setItems]               = useState(buildInitialItems)
  const [nextItemId, setNextItemId]     = useState((link?.items || 1) + 1)
  const [feeMode, setFeeMode]           = useState('hotel')
  const [clientFeePercent, setClientFeePercent] = useState(50)
  const [selectedDate, setSelectedDate] = useState(null)
  const [timeValue, setTimeValue]       = useState('14:00')
  const [calendarOpen, setCalendarOpen] = useState(false)
  const [showConfirmClose, setShowConfirmClose] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)

  const hasData = () => {
    const hasItems = items.some(it => it.desc.trim() !== '' || it.amount.trim() !== '')
    return hasItems || selectedDate !== null || feeMode !== 'hotel' || timeValue !== '14:00'
  }

  const handleClose = () => {
    if (hasData()) {
      setShowConfirmClose(true)
    } else {
      onClose()
    }
  }

  const addItem    = () => { setItems(prev => [...prev, { id: nextItemId, desc: '', amount: '' }]); setNextItemId(n => n + 1) }
  const removeItem = i  => setItems(prev => prev.filter((_, idx) => idx !== i))
  const updateItem = (i, field, val) => setItems(prev => prev.map((it, idx) => idx === i ? { ...it, [field]: val } : it))

  const handleGenerateLink = () => {
    setIsGenerating(true)
    setTimeout(() => { setIsGenerating(false); onClose() }, 1500)
  }

  const FEE_RATE = 0.03
  const subtotal = items.reduce((sum, it) => sum + (parseFloat(it.amount) || 0), 0)
  const totalFee = subtotal * FEE_RATE

  const clientFeeShare = feeMode === 'hotel' ? 0
    : feeMode === 'cliente' ? totalFee
    : totalFee * (clientFeePercent / 100)

  const total = subtotal + clientFeeShare

  const footer = (
    <div className="w-full space-y-4">
      {/* Fee bearer */}
      <div>
        <label className={`block text-[11px] font-bold tracking-wide mb-2 ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
          {t('links.bankFee')}
        </label>
        <SegmentControl
          options={[
            { value: 'hotel', label: t('refund.hotelBearer') },
            { value: 'shared', label: t('links.feeShared') },
            { value: 'cliente', label: t('refund.clientBearer') },
          ]}
          value={feeMode}
          onChange={setFeeMode}
        />
      </div>

      {/* Slider for shared mode */}
      <AnimatePresence>
        {feeMode === 'shared' && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ type: 'spring', stiffness: 400, damping: 30 }}
            className="overflow-hidden"
          >
            <div className={`rounded-xl p-3 ${isDarkMode ? 'bg-[#111113]/40 border border-white/5' : 'bg-gray-50/80 border border-black/5'}`}>
              <input
                type="range"
                min={10}
                max={90}
                step={10}
                value={clientFeePercent}
                onChange={e => setClientFeePercent(Number(e.target.value))}
                className="w-full h-1.5 rounded-full appearance-none cursor-pointer accent-[#7C3AED] bg-gradient-to-r from-[#7C3AED]/20 to-[#7C3AED]/60"
                style={{
                  background: `linear-gradient(to right, ${isDarkMode ? '#7C3AED33' : '#7C3AED22'} 0%, ${isDarkMode ? '#7C3AED99' : '#7C3AED'} 100%)`,
                }}
              />
              <div className="flex justify-between mt-2">
                <span className={`text-[11px] font-bold ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
                  {t('links.feeHotelShare', { percent: 100 - clientFeePercent })}
                </span>
                <span className={`text-[11px] font-bold text-[#7C3AED]`}>
                  {t('links.feeClientShare', { percent: clientFeePercent })}
                </span>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Summary breakdown */}
      <div className={`rounded-xl p-3 space-y-2 font-mono text-xs ${isDarkMode ? 'bg-[#111113]/60 border border-white/5' : 'bg-gray-50 border border-black/5'}`}>
        <div className={`flex justify-between ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
          <span>{t('links.subtotal')} ({items.length}):</span>
          <span className={isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]'}>${subtotal.toFixed(2)}</span>
        </div>

        {feeMode === 'hotel' && (
          <div className={`flex justify-between ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
            <span>{t('links.stripeFee')}:</span>
            <span>{t('links.absorbed')}</span>
          </div>
        )}

        {feeMode === 'cliente' && (
          <div className={`flex justify-between ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
            <span>{t('links.feeClientLabel', { percent: 100 })}:</span>
            <span className={isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]'}>+${clientFeeShare.toFixed(2)}</span>
          </div>
        )}

        {feeMode === 'shared' && (
          <>
            <div className={`flex justify-between ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
              <span>{t('links.feeHotelLabel', { percent: 100 - clientFeePercent })}:</span>
              <span>{t('links.absorbed')}</span>
            </div>
            <div className={`flex justify-between ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
              <span>{t('links.feeClientLabel', { percent: clientFeePercent })}:</span>
              <span className={isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]'}>+${clientFeeShare.toFixed(2)}</span>
            </div>
          </>
        )}

        <div className={`flex justify-between items-end pt-2 mt-1 border-t ${isDarkMode ? 'border-white/10' : 'border-gray-200'}`}>
          <span className={`font-sans font-bold text-sm ${isDarkMode ? 'text-white' : 'text-[#111113]'}`}>
            {t('links.totalCharge')}:
          </span>
          <span className="text-2xl font-bold tracking-tighter text-[#7C3AED]">
            ${total.toFixed(2)}
          </span>
        </div>
      </div>

      {/* CTA */}
      <Button
        className="w-full !py-4 shadow-lg relative overflow-hidden"
        onClick={handleGenerateLink}
        disabled={isGenerating || !selectedDate || subtotal === 0}
      >
        {isGenerating ? (
          <span className="flex items-center gap-2">
            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin-slow" />
            {isEditing ? t('links.saving') : t('common.generating')}...
          </span>
        ) : (
          <span className="flex items-center gap-2">
            <LinkIcon size={18} /> {isEditing ? t('links.saveChanges') : t('links.generateLink')}
          </span>
        )}
      </Button>
    </div>
  )

  return (
    <>
      {/* Confirmation sub-modal */}
      <AnimatePresence>
        {showConfirmClose && (
          <motion.div
            exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            className="fixed inset-0 z-[60] flex items-center justify-center p-4"
          >
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.15 }}
              className="absolute inset-0 backdrop-blur-md bg-black/60"
              onClick={() => setShowConfirmClose(false)}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 10 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 10 }}
              transition={{
                opacity: { duration: 0.15 },
                scale: { type: 'spring', stiffness: 400, damping: 26 },
                y: { type: 'spring', stiffness: 400, damping: 26 },
              }}
              className={`relative p-6 rounded-2xl border shadow-2xl max-w-[360px] ${
                isDarkMode ? 'bg-[#252429] border-white/20' : 'bg-white border-gray-200'
              }`}
            >
              <h3 className={`text-lg font-bold mb-2 ${isDarkMode ? 'text-white' : 'text-[#111113]'}`}>
                {t('common.discardConfirmTitle')}
              </h3>
              <p className={`text-sm mb-6 ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
                {t('common.discardConfirmBody')}
              </p>
              <div className="flex gap-3 justify-end">
                <Button variant="ghost" onClick={() => setShowConfirmClose(false)}>
                  {t('common.cancel')}
                </Button>
                <Button variant="danger" onClick={onClose}>
                  {t('common.discardConfirmAction')}
                </Button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Date picker modal — z-[55] to stack above parent modal (z-50) */}
      {calendarOpen && (
        <div className="relative z-[55]">
          <DatePickerModal
            selectedDate={selectedDate}
            onSelect={setSelectedDate}
            timeValue={timeValue}
            onTimeChange={setTimeValue}
            onConfirm={() => setCalendarOpen(false)}
            onClose={() => setCalendarOpen(false)}
          />
        </div>
      )}

      <Modal
        onClose={handleClose}
        icon={<LinkIcon size={24} />}
        title={isEditing ? t('links.editLink') : t('links.createLink')}
        description={isDesktop ? (isEditing ? t('links.editLinkDesc') : t('links.generateDescription')) : undefined}
        maxWidth="580px"
        footer={footer}
        className="max-h-[95vh] sm:max-h-[90vh] flex flex-col"
      >
        <div className="p-5 sm:p-8 space-y-6">

          {/* ── Fecha de expiración ── */}
          <div>
            <SectionLabel className="flex items-center gap-2 mb-4">
              <CalendarDays size={14} /> {t('links.expirationDate')}
            </SectionLabel>
            <Button
              variant="outline"
              className={`w-full justify-start text-left font-normal ${!selectedDate && (isDarkMode ? '!text-[#888991]' : '!text-[#B0AFB4]')}`}
              onClick={() => setCalendarOpen(true)}
            >
              <CalendarDays size={16} className={`mr-2 flex-shrink-0 ${selectedDate ? 'text-[#7C3AED]' : 'opacity-50'}`} />
              <span className="truncate">
                {selectedDate ? `${selectedDate} – ${timeValue}` : t('links.selectDateTime')}
              </span>
            </Button>
          </div>

          {/* ── Cliente ── */}
          <div>
            <SectionLabel className="flex items-center gap-2 mb-4">
              <User size={14} /> {t('links.clientData')}
            </SectionLabel>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className={`block text-xs font-bold tracking-wide mb-2 ${isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]'}`}>
                  {t('links.clientName')}
                </label>
                <Input type="text" placeholder={t('links.clientNamePlaceholder')} />
              </div>
              <div>
                <label className={`block text-xs font-bold tracking-wide mb-2 ${isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]'}`}>
                  {t('links.clientEmail')}
                </label>
                <Input icon={Mail} type="email" placeholder={t('links.clientEmailPlaceholder')} />
              </div>
            </div>
          </div>

          {/* ── Items ── */}
          <div>
            <div className="flex justify-between items-center mb-4">
              <SectionLabel className="flex items-center gap-2">
                <ListTree size={14} /> {t('links.itemBuilder')}
              </SectionLabel>
              <Button variant="outline" size="sm" onClick={addItem} className="!h-8 !px-3">
                <Plus size={14} /> {t('links.addItem')}
              </Button>
            </div>

            <div className={`p-4 rounded-2xl border space-y-3 ${isDarkMode ? 'bg-[#111113]/30 border-white/5' : 'bg-gray-50/50 border-black/5'}`}>
              {items.map((item, idx) => (
                <div key={item.id} className="flex gap-2 sm:gap-3 items-start animate-fade-in">
                  <div className="flex-1 min-w-0">
                    <Input
                      type="text"
                      placeholder={t('links.conceptPlaceholder')}
                      value={item.desc}
                      onChange={e => updateItem(idx, 'desc', e.target.value)}
                    />
                  </div>
                  <div className="w-28 sm:w-32 flex-shrink-0">
                    <Input
                      type="number"
                      min="0"
                      placeholder={t('links.price')}
                      value={item.amount}
                      onChange={e => updateItem(idx, 'amount', e.target.value)}
                    />
                  </div>
                  {items.length > 1 ? (
                    <Button variant="danger" size="icon" onClick={() => removeItem(idx)} className="flex-shrink-0 mt-1">
                      <Trash2 size={16} />
                    </Button>
                  ) : (
                    <Button variant="ghost" size="icon" disabled className="flex-shrink-0 mt-1 opacity-20 cursor-not-allowed">
                      <Trash2 size={16} />
                    </Button>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      </Modal>
    </>
  )
}

// app/components/features/links/NewLinkModal.vue
<script setup>
import { ref, computed } from 'vue'
import { motion, AnimatePresence } from 'motion-v'
import {
  Plus, Trash2, Mail, User, ListTree,
  Link as LinkIcon, CalendarDays,
} from 'lucide-vue-next'
import { useThemeStore } from '~/stores/theme'
import { useMediaQuery } from '~/composables/useMediaQuery'
import { SPRING } from '~/utils/springs'
import Modal from '~/components/ui/Modal.vue'
import Button from '~/components/ui/Button.vue'
import Input from '~/components/ui/Input.vue'
import SegmentControl from '~/components/ui/SegmentControl.vue'
import SectionLabel from '~/components/ui/SectionLabel.vue'
import DatePickerModal from '~/components/ui/DatePickerModal.vue'

const props = defineProps({
  link: { type: Object, default: null },
})
const emit = defineEmits(['close'])

const { t } = useI18n()
const themeStore = useThemeStore()
const isDesktop = useMediaQuery('(min-width: 640px)')
const isEditing = computed(() => !!props.link)

const buildInitialItems = () => {
  if (!props.link) return [{ id: 1, desc: '', amount: '' }]
  const count = props.link.items || 1
  return Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    desc: i === 0 ? (props.link.client || '') : '',
    amount: i === 0 ? (props.link.amount?.replace(/,/g, '') || '') : '',
  }))
}

const items = ref(buildInitialItems())
const nextItemId = ref((props.link?.items || 1) + 1)
const feeMode = ref('hotel')
const clientFeePercent = ref(50)
const selectedDate = ref(null)
const timeValue = ref('14:00')
const calendarOpen = ref(false)
const showConfirmClose = ref(false)
const isGenerating = ref(false)

const hasData = computed(() => {
  const hasItems = items.value.some(it => it.desc.trim() !== '' || it.amount.trim() !== '')
  return hasItems || selectedDate.value !== null || feeMode.value !== 'hotel' || timeValue.value !== '14:00'
})

const handleClose = () => {
  if (hasData.value) showConfirmClose.value = true
  else emit('close')
}

const addItem = () => {
  items.value.push({ id: nextItemId.value, desc: '', amount: '' })
  nextItemId.value += 1
}
const removeItem = (i) => { items.value.splice(i, 1) }
const updateItem = (i, field, val) => { items.value[i][field] = val }

const handleGenerate = () => {
  isGenerating.value = true
  setTimeout(() => { isGenerating.value = false; emit('close') }, 1500)
}

const FEE_RATE = 0.03
const subtotal = computed(() => items.value.reduce((s, it) => s + (parseFloat(it.amount) || 0), 0))
const totalFee = computed(() => subtotal.value * FEE_RATE)
const clientFeeShare = computed(() => {
  if (feeMode.value === 'hotel') return 0
  if (feeMode.value === 'cliente') return totalFee.value
  return totalFee.value * (clientFeePercent.value / 100)
})
const total = computed(() => subtotal.value + clientFeeShare.value)

const feeOptions = computed(() => [
  { value: 'hotel', label: t('refund.hotelBearer') },
  { value: 'shared', label: t('links.feeShared') },
  { value: 'cliente', label: t('refund.clientBearer') },
])

const sliderStyle = computed(() => ({
  background: `linear-gradient(to right, ${themeStore.isDarkMode ? '#7C3AED33' : '#7C3AED22'} 0%, ${themeStore.isDarkMode ? '#7C3AED99' : '#7C3AED'} 100%)`,
}))
</script>

<template>
  <!-- Date picker (z-[55] above parent modal) -->
  <div v-if="calendarOpen" class="relative z-[55]">
    <DatePickerModal
      :selected-date="selectedDate"
      :time-value="timeValue"
      @select="selectedDate = $event"
      @time-change="timeValue = $event"
      @confirm="calendarOpen = false"
      @close="calendarOpen = false"
    />
  </div>

  <Modal
    :title="isEditing ? t('links.editLink') : t('links.createLink')"
    :description="isDesktop ? (isEditing ? t('links.editLinkDesc') : t('links.generateDescription')) : ''"
    :icon="LinkIcon"
    max-width="580px"
    wrapper-class="max-h-[95vh] sm:max-h-[90vh] flex flex-col"
    @close="handleClose"
  >
    <div class="p-5 sm:p-8 space-y-6">
      <!-- Fecha -->
      <div>
        <SectionLabel class="flex items-center gap-2 mb-4">
          <CalendarDays :size="14" /> {{ t('links.expirationDate') }}
        </SectionLabel>
        <Button
          variant="outline"
          :class="[
            'w-full justify-start text-left font-normal',
            !selectedDate ? (themeStore.isDarkMode ? '!text-[#888991]' : '!text-[#B0AFB4]') : ''
          ]"
          @click="calendarOpen = true"
        >
          <CalendarDays :size="16" :class="['mr-2 shrink-0', selectedDate ? 'text-[#7C3AED]' : 'opacity-50']" />
          <span class="truncate">
            {{ selectedDate ? `${selectedDate} – ${timeValue}` : t('links.selectDateTime') }}
          </span>
        </Button>
      </div>

      <!-- Cliente -->
      <div>
        <SectionLabel class="flex items-center gap-2 mb-4">
          <User :size="14" /> {{ t('links.clientData') }}
        </SectionLabel>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label for="link-client-name" :class="['block text-xs font-bold tracking-wide mb-2', themeStore.isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]']">
              {{ t('links.clientName') }}
            </label>
            <Input id="link-client-name" type="text" :placeholder="t('links.clientNamePlaceholder')" />
          </div>
          <div>
            <label for="link-client-email" :class="['block text-xs font-bold tracking-wide mb-2', themeStore.isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]']">
              {{ t('links.clientEmail') }}
            </label>
            <Input id="link-client-email" :icon="Mail" type="email" placeholder="alice@example.com" />
          </div>
        </div>
      </div>

      <!-- Items -->
      <div>
        <div class="flex justify-between items-center mb-4">
          <SectionLabel class="flex items-center gap-2">
            <ListTree :size="14" /> {{ t('links.itemBuilder') }}
          </SectionLabel>
          <Button variant="outline" size="sm" class="!h-8 !px-3" @click="addItem">
            <Plus :size="14" /> {{ t('links.addItem') }}
          </Button>
        </div>
        <div :class="['p-4 rounded-2xl border space-y-3', themeStore.isDarkMode ? 'bg-[#111113]/30 border-white/5' : 'bg-gray-50/50 border-black/5']">
          <div v-for="(item, idx) in items" :key="item.id" class="flex gap-2 sm:gap-3 items-start animate-fade-in">
            <div class="flex-1 min-w-0">
              <Input
                type="text"
                :placeholder="t('links.conceptPlaceholder')"
                :model-value="item.desc"
                @update:model-value="updateItem(idx, 'desc', $event)"
              />
            </div>
            <div class="w-28 sm:w-32 shrink-0">
              <Input
                type="number"
                min="0"
                :placeholder="t('links.price')"
                :model-value="item.amount"
                @update:model-value="updateItem(idx, 'amount', $event)"
              />
            </div>
            <Button v-if="items.length > 1" variant="danger" size="icon" class="shrink-0 mt-1" @click="removeItem(idx)">
              <Trash2 :size="16" />
            </Button>
            <Button v-else variant="ghost" size="icon" disabled class="shrink-0 mt-1 opacity-20 cursor-not-allowed">
              <Trash2 :size="16" />
            </Button>
          </div>
        </div>
      </div>
    </div>

    <template #footer>
      <div class="w-full space-y-4">
        <div>
          <label :class="['block text-[11px] font-bold tracking-wide mb-2', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
            {{ t('links.bankFee') }}
          </label>
          <SegmentControl v-model="feeMode" :options="feeOptions" />
        </div>

        <AnimatePresence>
          <motion.div
            v-if="feeMode === 'shared'"
            :initial="{ opacity: 0, height: 0 }"
            :animate="{ opacity: 1, height: 'auto' }"
            :exit="{ opacity: 0, height: 0 }"
            :transition="SPRING"
            class="overflow-hidden"
          >
            <div :class="['rounded-xl p-3', themeStore.isDarkMode ? 'bg-[#111113]/40 border border-white/5' : 'bg-gray-50/80 border border-black/5']">
              <input
                type="range"
                min="10"
                max="90"
                step="10"
                :value="clientFeePercent"
                class="w-full h-1.5 rounded-full appearance-none cursor-pointer accent-[#7C3AED]"
                :style="sliderStyle"
                @input="clientFeePercent = Number($event.target.value)"
              />
              <div class="flex justify-between mt-2">
                <span :class="['text-[11px] font-bold', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
                  {{ t('links.feeHotelShare', { percent: 100 - clientFeePercent }) }}
                </span>
                <span class="text-[11px] font-bold text-[#7C3AED]">
                  {{ t('links.feeClientShare', { percent: clientFeePercent }) }}
                </span>
              </div>
            </div>
          </motion.div>
        </AnimatePresence>

        <div :class="['rounded-xl p-3 space-y-2 font-mono text-xs', themeStore.isDarkMode ? 'bg-[#111113]/60 border border-white/5' : 'bg-gray-50 border border-black/5']">
          <div :class="['flex justify-between', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
            <span>{{ t('links.subtotal') }} ({{ items.length }}):</span>
            <span :class="themeStore.isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]'">${{ subtotal.toFixed(2) }}</span>
          </div>
          <div v-if="feeMode === 'hotel'" :class="['flex justify-between', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
            <span>{{ t('links.stripeFee') }}:</span>
            <span>{{ t('links.absorbed') }}</span>
          </div>
          <div v-if="feeMode === 'cliente'" :class="['flex justify-between', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
            <span>{{ t('links.feeClientLabel', { percent: 100 }) }}:</span>
            <span :class="themeStore.isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]'">+${{ clientFeeShare.toFixed(2) }}</span>
          </div>
          <template v-if="feeMode === 'shared'">
            <div :class="['flex justify-between', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
              <span>{{ t('links.feeHotelLabel', { percent: 100 - clientFeePercent }) }}:</span>
              <span>{{ t('links.absorbed') }}</span>
            </div>
            <div :class="['flex justify-between', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
              <span>{{ t('links.feeClientLabel', { percent: clientFeePercent }) }}:</span>
              <span :class="themeStore.isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]'">+${{ clientFeeShare.toFixed(2) }}</span>
            </div>
          </template>
          <div :class="['flex justify-between items-end pt-2 mt-1 border-t', themeStore.isDarkMode ? 'border-white/10' : 'border-gray-200']">
            <span :class="['font-sans font-bold text-sm', themeStore.isDarkMode ? 'text-white' : 'text-[#111113]']">
              {{ t('links.totalCharge') }}:
            </span>
            <span class="text-2xl font-bold tracking-tighter text-[#7C3AED]">${{ total.toFixed(2) }}</span>
          </div>
        </div>

        <Button
          class="w-full !py-4 shadow-lg relative overflow-hidden"
          :disabled="isGenerating || !selectedDate || subtotal === 0"
          @click="handleGenerate"
        >
          <span v-if="isGenerating" class="flex items-center gap-2">
            <div class="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin-slow" />
            {{ isEditing ? t('links.saving') : t('common.generating') }}...
          </span>
          <span v-else class="flex items-center gap-2">
            <LinkIcon :size="18" /> {{ isEditing ? t('links.saveChanges') : t('links.generateLink') }}
          </span>
        </Button>
      </div>
    </template>
  </Modal>

  <!-- Confirm close sub-modal -->
  <AnimatePresence>
    <Modal
      v-if="showConfirmClose"
      :title="t('common.discardConfirmTitle')"
      max-width="360px"
      @close="showConfirmClose = false"
    >
      <p :class="['px-5 sm:px-8 py-5 text-sm', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
        {{ t('common.discardConfirmBody') }}
      </p>
      <template #footer>
        <Button variant="ghost" class="flex-1" @click="showConfirmClose = false">{{ t('common.cancel') }}</Button>
        <Button variant="danger" class="flex-1" @click="emit('close')">{{ t('common.discardConfirmAction') }}</Button>
      </template>
    </Modal>
  </AnimatePresence>
</template>
