// src/features/dashboard/components/KpiCard.jsx
import { StatCard } from '@/shared/ui'

export default function KpiCard({ kpi }) {
  // Only show "vs. ayer" suffix for percentage-based changes
  const isComparative = typeof kpi.change === 'string' && kpi.change.includes('%')

  return (
    <StatCard
      label={kpi.label}
      value={kpi.value}
      icon={kpi.icon}
      iconVariant={kpi.variant === 'default' ? 'default' : kpi.variant}
      badge={kpi.change}
      badgeVariant={kpi.variant === 'default' ? 'outline' : kpi.variant}
      badgeSuffix={isComparative ? 'vs. ayer' : undefined}
    />
  )
}

// app/components/features/dashboard/KpiCard.vue
<script setup>
import { computed } from 'vue'
import StatCard from '~/components/ui/StatCard.vue'

const props = defineProps({ kpi: { type: Object, required: true } })

const isComparative = computed(() => typeof props.kpi.change === 'string' && props.kpi.change.includes('%'))
const iconVariant = computed(() => props.kpi.variant === 'default' ? 'default' : props.kpi.variant)
const badgeVariant = computed(() => props.kpi.variant === 'default' ? 'outline' : props.kpi.variant)
</script>

<template>
  <StatCard
    :label="kpi.label"
    :value="kpi.value"
    :icon="kpi.icon"
    :icon-variant="iconVariant"
    :badge="kpi.change"
    :badge-variant="badgeVariant"
    :badge-suffix="isComparative ? 'vs. ayer' : ''"
  />
</template>
