// app/components/features/dashboard/ChartCard.vue
<script setup>
import { ref, computed } from 'vue'
import { motion, AnimatePresence } from 'motion-v'
import { CreditCard } from 'lucide-vue-next'
import Card from '~/components/ui/Card.vue'
import SegmentControl from '~/components/ui/SegmentControl.vue'
import { useThemeStore } from '~/stores/theme'
import { CHART_DATA, CONVERSION_DATA, PAYMENT_METHODS } from '~/utils/mockData'

const { t } = useI18n()
const themeStore = useThemeStore()
const chart = ref('volumen')

const CHART_TITLES = computed(() => ({
  volumen: { h: t('dashboard.volumeByChannel'), sub: t('dashboard.volumeByChannelDesc') },
  conversion: { h: t('dashboard.conversionRate'), sub: t('dashboard.conversionRateDesc') },
  metodos: { h: t('dashboard.paymentMethods'), sub: t('dashboard.paymentMethodsDesc') },
}))

const FADE_SPRING = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { type: 'spring', stiffness: 300, damping: 24 } },
  exit: { opacity: 0, transition: { duration: 0.15 } },
}

const segmentOptions = computed(() => [
  { value: 'volumen', label: t('dashboard.volume') },
  { value: 'conversion', label: t('dashboard.conversion') },
  { value: 'metodos', label: t('dashboard.methods') },
])

// ── Volumen: SVG area chart (replaces recharts) ──
const hoverIdx = ref(-1)

const svgW = 520
const svgH = 200
const padL = 40, padR = 10, padT = 10, padB = 30

const chartX = (i, len) => padL + (i * (svgW - padL - padR) / Math.max(1, len - 1))
const maxY = computed(() => {
  let max = 0
  CHART_DATA.forEach(d => {
    if (d.links > max) max = d.links
    if (d.pos > max) max = d.pos
  })
  return Math.ceil(max / 1000) * 1000 || 1000
})
const chartY = (v) => padT + (svgH - padT - padB) * (1 - v / maxY.value)

const makeAreaPath = (key) => {
  const n = CHART_DATA.length
  let d = `M ${chartX(0, n)} ${chartY(CHART_DATA[0][key])}`
  for (let i = 1; i < n; i++) {
    const x0 = chartX(i - 1, n), y0 = chartY(CHART_DATA[i - 1][key])
    const x1 = chartX(i, n), y1 = chartY(CHART_DATA[i][key])
    const cx = (x0 + x1) / 2
    d += ` C ${cx} ${y0}, ${cx} ${y1}, ${x1} ${y1}`
  }
  d += ` L ${chartX(n - 1, n)} ${svgH - padB} L ${chartX(0, n)} ${svgH - padB} Z`
  return d
}
const makeLinePath = (key) => {
  const n = CHART_DATA.length
  let d = `M ${chartX(0, n)} ${chartY(CHART_DATA[0][key])}`
  for (let i = 1; i < n; i++) {
    const x0 = chartX(i - 1, n), y0 = chartY(CHART_DATA[i - 1][key])
    const x1 = chartX(i, n), y1 = chartY(CHART_DATA[i][key])
    const cx = (x0 + x1) / 2
    d += ` C ${cx} ${y0}, ${cx} ${y1}, ${x1} ${y1}`
  }
  return d
}

const areaLinks = computed(() => makeAreaPath('links'))
const areaPos = computed(() => makeAreaPath('pos'))
const lineLinks = computed(() => makeLinePath('links'))
const linePos = computed(() => makeLinePath('pos'))

const yTicks = computed(() => {
  const step = maxY.value / 4
  return [0, step, step * 2, step * 3, maxY.value]
})

const gridStroke = computed(() => themeStore.isDarkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)')
const axisTick = computed(() => themeStore.isDarkMode ? '#888991' : '#A1A1AA')

const onHover = (e) => {
  const svg = e.currentTarget
  const rect = svg.getBoundingClientRect()
  const x = ((e.clientX - rect.left) / rect.width) * svgW
  const n = CHART_DATA.length
  let closest = 0, best = Infinity
  for (let i = 0; i < n; i++) {
    const cx = chartX(i, n)
    const d = Math.abs(x - cx)
    if (d < best) { best = d; closest = i }
  }
  hoverIdx.value = closest
}
const onLeave = () => { hoverIdx.value = -1 }

const tooltipClass = computed(() =>
  themeStore.isDarkMode
    ? 'bg-[#252429]/90 border-white/10 text-white'
    : 'bg-white/90 border-[#7C3AED]/20 text-[#111113]',
)
</script>

<template>
  <Card class="lg:col-span-2 p-8 flex flex-col">
    <div class="flex flex-col sm:flex-row justify-between items-start gap-4 mb-8">
      <div>
        <h3 :class="['font-bold text-lg', themeStore.isDarkMode ? 'text-white' : 'text-[#111113]']">{{ CHART_TITLES[chart].h }}</h3>
        <p :class="['text-xs font-medium mt-1', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">{{ CHART_TITLES[chart].sub }}</p>
      </div>
      <SegmentControl v-model="chart" :options="segmentOptions" layout-id="chartTabIndicator" />
    </div>

    <div class="flex-1 relative min-h-[220px] flex items-end">
      <AnimatePresence mode="wait">
        <!-- Volumen: SVG area -->
        <motion.div
          v-if="chart === 'volumen'"
          key="volumen"
          :variants="FADE_SPRING"
          initial="hidden"
          animate="show"
          exit="exit"
          class="w-full h-[200px] relative"
        >
          <svg
            :viewBox="`0 0 ${svgW} ${svgH}`"
            preserveAspectRatio="none"
            class="w-full h-full"
            @mousemove="onHover"
            @mouseleave="onLeave"
          >
            <defs>
              <linearGradient id="purpleGrad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stop-color="#7C3AED" stop-opacity="0.3" />
                <stop offset="95%" stop-color="#7C3AED" stop-opacity="0" />
              </linearGradient>
              <linearGradient id="emeraldGrad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stop-color="#10B981" stop-opacity="0.3" />
                <stop offset="95%" stop-color="#10B981" stop-opacity="0" />
              </linearGradient>
            </defs>

            <!-- Grid -->
            <line v-for="(y, i) in yTicks" :key="`g-${i}`" :x1="padL" :x2="svgW - padR" :y1="chartY(y)" :y2="chartY(y)" :stroke="gridStroke" stroke-dasharray="4 4" />

            <!-- Y axis labels -->
            <text
              v-for="(y, i) in yTicks"
              :key="`yl-${i}`"
              :x="padL - 6"
              :y="chartY(y) + 4"
              text-anchor="end"
              :fill="axisTick"
              font-size="11"
              font-weight="600"
            >${{ y / 1000 }}k</text>

            <!-- X axis labels -->
            <text
              v-for="(d, i) in CHART_DATA"
              :key="`xl-${i}`"
              :x="chartX(i, CHART_DATA.length)"
              :y="svgH - padB + 18"
              text-anchor="middle"
              :fill="axisTick"
              font-size="11"
              font-weight="600"
            >{{ d.name }}</text>

            <!-- Areas + lines -->
            <path :d="areaLinks" fill="url(#purpleGrad)" />
            <path :d="lineLinks" fill="none" stroke="#7C3AED" stroke-width="3" />
            <path :d="areaPos" fill="url(#emeraldGrad)" />
            <path :d="linePos" fill="none" stroke="#10B981" stroke-width="3" />

            <!-- Cursor + active dots -->
            <template v-if="hoverIdx >= 0">
              <line
                :x1="chartX(hoverIdx, CHART_DATA.length)"
                :x2="chartX(hoverIdx, CHART_DATA.length)"
                :y1="padT"
                :y2="svgH - padB"
                :stroke="themeStore.isDarkMode ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)'"
                stroke-width="1"
                stroke-dasharray="4 4"
              />
              <circle :cx="chartX(hoverIdx, CHART_DATA.length)" :cy="chartY(CHART_DATA[hoverIdx].links)" r="6" fill="#7C3AED" />
              <circle :cx="chartX(hoverIdx, CHART_DATA.length)" :cy="chartY(CHART_DATA[hoverIdx].pos)" r="6" fill="#10B981" />
            </template>
          </svg>

          <!-- Tooltip -->
          <div
            v-if="hoverIdx >= 0"
            :class="['absolute top-2 p-3 rounded-xl border backdrop-blur-md shadow-xl pointer-events-none transition-all', tooltipClass]"
            :style="{ left: `${(chartX(hoverIdx, CHART_DATA.length) / svgW) * 100}%`, transform: 'translateX(-50%)' }"
          >
            <p class="font-bold text-sm mb-2">{{ CHART_DATA[hoverIdx].name }}</p>
            <div class="flex items-center gap-2 text-xs font-medium mt-1">
              <div class="w-2 h-2 rounded-full" style="background-color: #7C3AED" />
              <span :class="themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'">{{ t('dashboard.chartPaymentLinks') }}:</span>
              <span class="font-mono font-bold">${{ CHART_DATA[hoverIdx].links.toLocaleString() }}</span>
            </div>
            <div class="flex items-center gap-2 text-xs font-medium mt-1">
              <div class="w-2 h-2 rounded-full" style="background-color: #10B981" />
              <span :class="themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'">{{ t('dashboard.chartTerminalPos') }}:</span>
              <span class="font-mono font-bold">${{ CHART_DATA[hoverIdx].pos.toLocaleString() }}</span>
            </div>
          </div>
        </motion.div>

        <!-- Conversion bars -->
        <motion.div
          v-else-if="chart === 'conversion'"
          key="conversion"
          :variants="FADE_SPRING"
          initial="hidden"
          animate="show"
          exit="exit"
          class="w-full h-[200px] flex items-end justify-between px-4 pb-6"
        >
          <div v-for="item in CONVERSION_DATA" :key="item.day" class="flex flex-col items-center gap-2 group cursor-pointer">
            <span :class="['text-[9px] font-bold opacity-0 group-hover:opacity-100 transition-opacity', themeStore.isDarkMode ? 'text-[#B9A4F8]' : 'text-[#7C3AED]']">
              {{ item.value }}%
            </span>
            <div
              :class="[
                'w-10 md:w-14 rounded-md relative flex items-end p-1 transition-colors',
                themeStore.isDarkMode ? 'bg-[#111113]/50 border border-white/5' : 'bg-gray-100 border border-black/5'
              ]"
              :style="{ height: '140px' }"
            >
              <div
                class="w-full rounded-sm transition-all duration-700 group-hover:brightness-125"
                :style="{
                  height: `${item.value}%`,
                  background: 'linear-gradient(to top, #561BAF, #7C3AED)',
                  boxShadow: '0 0 10px rgba(124,58,237,0.2)',
                }"
              />
            </div>
            <span :class="['text-[10px] font-bold', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#A1A1AA]']">{{ item.day }}</span>
          </div>
        </motion.div>

        <!-- Metodos: horizontal bars -->
        <motion.div
          v-else-if="chart === 'metodos'"
          key="metodos"
          :variants="FADE_SPRING"
          initial="hidden"
          animate="show"
          exit="exit"
          class="w-full h-[200px] flex flex-col justify-center gap-6 px-4"
        >
          <div v-for="item in PAYMENT_METHODS" :key="item.label" class="flex items-center gap-4">
            <div :class="['w-8 flex justify-center', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#A1A1AA]']">
              <CreditCard :size="20" />
            </div>
            <div class="flex-1">
              <div class="flex justify-between mb-1.5">
                <span :class="['text-xs font-bold', themeStore.isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]']">{{ item.label }}</span>
                <span class="text-xs font-mono font-bold" :style="{ color: item.color }">{{ item.val }}%</span>
              </div>
              <div :class="['h-2.5 rounded-full overflow-hidden', themeStore.isDarkMode ? 'bg-[#111113]' : 'bg-gray-200']">
                <div class="h-full rounded-full transition-all duration-1000" :style="{ width: `${item.val}%`, backgroundColor: item.color }" />
              </div>
            </div>
          </div>
        </motion.div>
      </AnimatePresence>
    </div>
  </Card>
</template>

// src/features/dashboard/components/ChartCard.jsx
import { useState } from 'react'
import { CreditCard } from 'lucide-react'
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer
} from 'recharts'
import { motion, AnimatePresence } from 'framer-motion'
import { useTranslation } from 'react-i18next'
import { useTheme } from '@/shared/context/ThemeContext'
import { Card, SegmentControl } from '@/shared/ui'

import { CHART_DATA, CONVERSION_DATA, PAYMENT_METHODS } from '@/services/mocks/mockData'

const FADE_SPRING = {
  hidden: { opacity: 0 },
  show:   { opacity: 1, transition: { type: 'spring', stiffness: 300, damping: 24 } },
  exit:   { opacity: 0, transition: { duration: 0.15 } },
}

function ChartTooltip({ active, payload, label, isDarkMode }) {
  if (active && payload && payload.length) {
    return (
      <div className={`p-3 rounded-xl border backdrop-blur-md shadow-xl ${
        isDarkMode 
          ? 'bg-[#252429]/90 border-white/10 text-white' 
          : 'bg-white/90 border-[#7C3AED]/20 text-[#111113]'
      }`}>
        <p className="font-bold text-sm mb-2">{label}</p>
        {payload.map(entry => (
          <div key={entry.name} className="flex items-center gap-2 text-xs font-medium mt-1">
            <div className="w-2 h-2 rounded-full" style={{ backgroundColor: entry.color }} />
            <span className={isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}>{entry.name}:</span>
            <span className="font-mono font-bold">${entry.value.toLocaleString()}</span>
          </div>
        ))}
      </div>
    )
  }
  return null
}

export default function ChartCard() {
  const { t }          = useTranslation()
  const { isDarkMode } = useTheme()
  const [chart, setChart] = useState('volumen')

  const CHART_TITLES = {
    volumen:    { h: t('dashboard.volumeByChannel'),  sub: t('dashboard.volumeByChannelDesc') },
    conversion: { h: t('dashboard.conversionRate'),   sub: t('dashboard.conversionRateDesc') },
    metodos:    { h: t('dashboard.paymentMethods'),   sub: t('dashboard.paymentMethodsDesc') },
  }

  return (
    <Card className="lg:col-span-2 p-8 flex flex-col">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start gap-4 mb-8">
        <div>
          <h3 className={`font-bold text-lg ${isDarkMode ? 'text-white' : 'text-[#111113]'}`}>
            {CHART_TITLES[chart].h}
          </h3>
          <p className={`text-xs font-medium mt-1 ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
            {CHART_TITLES[chart].sub}
          </p>
        </div>

        {/* Tab switcher */}
        <SegmentControl
          options={[
            { value: 'volumen',    label: t('dashboard.volume') },
            { value: 'conversion', label: t('dashboard.conversion') },
            { value: 'metodos',    label: t('dashboard.methods') },
          ]}
          value={chart}
          onChange={setChart}
          layoutId="chartTabIndicator"
        />
      </div>

      {/* Chart area */}
      <div className="flex-1 relative min-h-[220px] flex items-end">
        <AnimatePresence mode="wait">

        {/* ── Volumen: área line chart ── */}
        {chart === 'volumen' && (
          <motion.div key="volumen" variants={FADE_SPRING} initial="hidden" animate="show" exit="exit" className="w-full h-[200px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={CHART_DATA} margin={{ top: 10, right: 0, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="purpleGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#7C3AED" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#7C3AED" stopOpacity={0}/>
                  </linearGradient>
                  <linearGradient id="emeraldGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10B981" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#10B981" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid 
                  strokeDasharray="4 4" 
                  vertical={false} 
                  stroke={isDarkMode ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)'} 
                />
                <XAxis 
                  dataKey="name" 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fill: isDarkMode ? '#888991' : '#A1A1AA', fontSize: 11, fontWeight: 600 }}
                  dy={10}
                />
                <YAxis 
                  axisLine={false} 
                  tickLine={false} 
                  tick={{ fill: isDarkMode ? '#888991' : '#A1A1AA', fontSize: 11, fontWeight: 600 }}
                  tickFormatter={(val) => `$${val/1000}k`}
                />
                <Tooltip content={<ChartTooltip isDarkMode={isDarkMode} />} cursor={{ stroke: isDarkMode ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)', strokeWidth: 1, strokeDasharray: '4 4' }} />
                <Area 
                  type="monotone" 
                  dataKey="links" 
                  name={t('dashboard.chartPaymentLinks')}
                  stroke="#7C3AED" 
                  strokeWidth={3}
                  fillOpacity={1} 
                  fill="url(#purpleGrad)" 
                  activeDot={{ r: 6, strokeWidth: 0, fill: '#7C3AED' }}
                />
                <Area 
                  type="monotone" 
                  dataKey="pos" 
                  name={t('dashboard.chartTerminalPos')}
                  stroke="#10B981" 
                  strokeWidth={3}
                  fillOpacity={1} 
                  fill="url(#emeraldGrad)" 
                  activeDot={{ r: 6, strokeWidth: 0, fill: '#10B981' }}
                />
              </AreaChart>
            </ResponsiveContainer>
          </motion.div>
        )}

        {/* ── Conversión: bar chart ── */}
        {chart === 'conversion' && (
          <motion.div key="conversion" variants={FADE_SPRING} initial="hidden" animate="show" exit="exit" className="w-full h-[200px] flex items-end justify-between px-4 pb-6">
            {CONVERSION_DATA.map((item) => (
              <div key={item.day} className="flex flex-col items-center gap-2 group cursor-pointer">
                <span className={`text-[9px] font-bold opacity-0 group-hover:opacity-100 transition-opacity ${isDarkMode ? 'text-[#B9A4F8]' : 'text-[#7C3AED]'}`}>
                  {item.value}%
                </span>
                <div className={`w-10 md:w-14 rounded-md relative flex items-end p-1 transition-colors ${
                  isDarkMode ? 'bg-[#111113]/50 border border-white/5' : 'bg-gray-100 border border-black/5'
                }`} style={{ height: '140px' }}>
                  <div
                    className="w-full rounded-sm transition-all duration-700 group-hover:brightness-125"
                    style={{
                      height: `${item.value}%`,
                      background: 'linear-gradient(to top, #561BAF, #7C3AED)',
                      boxShadow: '0 0 10px rgba(124,58,237,0.2)',
                    }}
                  />
                </div>
                <span className={`text-[10px] font-bold ${isDarkMode ? 'text-[#888991]' : 'text-[#A1A1AA]'}`}>
                  {item.day}
                </span>
              </div>
            ))}
          </motion.div>
        )}

        {/* ── Métodos: horizontal bars ── */}
        {chart === 'metodos' && (
          <motion.div key="metodos" variants={FADE_SPRING} initial="hidden" animate="show" exit="exit" className="w-full h-[200px] flex flex-col justify-center gap-6 px-4">
            {PAYMENT_METHODS.map((item) => (
              <div key={item.label} className="flex items-center gap-4">
                <div className={`w-8 flex justify-center ${isDarkMode ? 'text-[#888991]' : 'text-[#A1A1AA]'}`}>
                  <CreditCard size={20} />
                </div>
                <div className="flex-1">
                  <div className="flex justify-between mb-1.5">
                    <span className={`text-xs font-bold ${isDarkMode ? 'text-[#D8D7D9]' : 'text-[#45434A]'}`}>
                      {item.label}
                    </span>
                    <span className="text-xs font-mono font-bold" style={{ color: item.color }}>
                      {item.val}%
                    </span>
                  </div>
                  <div className={`h-2.5 rounded-full overflow-hidden ${isDarkMode ? 'bg-[#111113]' : 'bg-gray-200'}`}>
                    <div
                      className="h-full rounded-full transition-all duration-1000"
                      style={{ width: `${item.val}%`, backgroundColor: item.color }}
                    />
                  </div>
                </div>
              </div>
            ))}
          </motion.div>
        )}
        </AnimatePresence>
      </div>
    </Card>
  )
}
