// app/components/features/dashboard/DashboardView.vue
<script setup>
import { ref } from 'vue'
import { motion, AnimatePresence } from 'motion-v'
import { Plus } from 'lucide-vue-next'
import { useViewSearch } from '~/composables/useViewSearch'
import { useThemeStore } from '~/stores/theme'
import { pageVariants } from '~/utils/motionVariants'
import { KPIS } from '~/utils/mockData'
import { ROUTES } from '~/utils/routes'
import Button from '~/components/ui/Button.vue'
import SegmentControl from '~/components/ui/SegmentControl.vue'
import KpiCard from './KpiCard.vue'
import QuickLinkCard from './QuickLinkCard.vue'
import ChartCard from './ChartCard.vue'
import LiveFeed from './LiveFeed.vue'
import PendingCharges from './PendingCharges.vue'
import NewLinkModal from '~/components/features/links/NewLinkModal.vue'

const { t } = useI18n()
const themeStore = useThemeStore()
useViewSearch('')

const newLinkOpen = ref(false)
const activeTab = ref('operations')

const segmentOptions = computed(() => [
  { value: 'operations', label: t('dashboard.tabOperations') },
  { value: 'metrics', label: t('dashboard.tabMetrics') },
])

const goTransactions = () => navigateTo(ROUTES.TRANSACTIONS)
</script>

<template>
  <motion.div :variants="pageVariants" initial="hidden" animate="show" exit="exit">
    <div class="flex flex-col sm:flex-row sm:items-center gap-4 sm:gap-6 mb-6 sm:mb-8">
      <h1 :class="['text-xl sm:text-2xl font-bold tracking-tight hidden sm:block', themeStore.isDarkMode ? 'text-white' : 'text-[#111113]']">
        {{ t('nav.dashboard') }}
      </h1>

      <div class="flex-1 sm:max-w-xs">
        <SegmentControl v-model="activeTab" :options="segmentOptions" layout-id="dashboardTab" />
      </div>

      <Button class="hidden sm:flex sm:ml-auto" @click="newLinkOpen = true">
        <Plus :size="18" /> {{ t('dashboard.newReservationLink') }}
      </Button>
    </div>

    <div class="sm:hidden mb-6">
      <Button size="lg" class="w-full" @click="newLinkOpen = true">
        <Plus :size="18" /> {{ t('dashboard.newReservationLink') }}
      </Button>
    </div>

    <template v-if="activeTab === 'operations'">
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 2xl:gap-8 mb-6 sm:mb-8">
        <QuickLinkCard />
        <LiveFeed @view-all="goTransactions" />
      </div>
      <div class="grid grid-cols-1 gap-4 sm:gap-6 2xl:gap-8">
        <PendingCharges />
      </div>
    </template>

    <template v-if="activeTab === 'metrics'">
      <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 sm:gap-6 2xl:gap-8 mb-6 sm:mb-8">
        <KpiCard v-for="kpi in KPIS" :key="kpi.label" :kpi="kpi" />
      </div>
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 2xl:gap-8">
        <ChartCard />
      </div>
    </template>

    <AnimatePresence>
      <NewLinkModal v-if="newLinkOpen" key="new-link" @close="newLinkOpen = false" />
    </AnimatePresence>
  </motion.div>
</template>

// src/features/dashboard/components/DashboardView.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Plus } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { useTranslation } from 'react-i18next'
import { useViewSearch } from '@/shared/context/ViewSearchContext'
import { pageVariants } from '@/shared/utils/motionVariants'
import { Button, PageHeader, SegmentControl } from '@/shared/ui'
import { KPIS, CURRENT_USER } from '@/services/mocks/mockData'
import { ROUTES } from '@/router/routes'
import KpiCard        from './KpiCard'
import QuickLinkCard  from './QuickLinkCard'
import ChartCard      from './ChartCard'
import LiveFeed       from './LiveFeed'
import AlertsPanel    from './AlertsPanel'
import PendingCharges from './PendingCharges'
import QuickActions   from './QuickActions'
import ShiftSummary   from './ShiftSummary'
// Cross-feature dependency: Dashboard reuses the NewLinkModal from links feature
// via its public re-export. This avoids duplicating the modal component.
import { NewLinkModal } from '@/features/links'

export default function DashboardView() {
  const { t }          = useTranslation()
  const navigate       = useNavigate()
  useViewSearch()
  const [newLinkOpen, setNewLinkOpen] = useState(false)
  const [activeTab, setActiveTab]     = useState('operations')

  return (
    <motion.div variants={pageVariants} initial="hidden" animate="show">
      <PageHeader
        title={t('dashboard.greeting', { name: CURRENT_USER.displayName })}
        description={t('dashboard.subtitle')}
        className="mb-6"
      >
        <Button onClick={() => setNewLinkOpen(true)} className="hidden sm:flex">
          <Plus size={18} /> {t('dashboard.newReservationLink')}
        </Button>
      </PageHeader>

      {/* Sub-view selector */}
      <div className="max-w-xs mb-6 sm:mb-8">
        <SegmentControl
          options={[
            { value: 'operations', label: t('dashboard.tabOperations') },
            { value: 'metrics',    label: t('dashboard.tabMetrics') },
          ]}
          value={activeTab}
          onChange={setActiveTab}
          layoutId="dashboardTab"
        />
      </div>

      {/* Mobile only: Full-width button */}
      <div className="sm:hidden mb-6">
        <Button size="lg" className="w-full" onClick={() => setNewLinkOpen(true)}>
          <Plus size={18} /> {t('dashboard.newReservationLink')}
        </Button>
      </div>

      {activeTab === 'operations' && (
        <>
          {/* Row 1: Cobro Rápido + Live Feed */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 2xl:gap-8 mb-6 sm:mb-8">
            <QuickLinkCard />
            <LiveFeed onViewAll={() => navigate(ROUTES.TRANSACTIONS)} />
          </div>

          {/* Row 2: Cobros Pendientes + Acciones/Resumen */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 2xl:gap-8 mb-6 sm:mb-8">
            <PendingCharges />
            <div className="flex flex-col gap-4 sm:gap-6 2xl:gap-8">
              <QuickActions onNewCharge={() => setNewLinkOpen(true)} />
              <ShiftSummary />
            </div>
          </div>

          {/* Row 3: Requiere Atención */}
          <div className="grid grid-cols-1 gap-4 sm:gap-6 2xl:gap-8">
            <AlertsPanel />
          </div>
        </>
      )}

      {activeTab === 'metrics' && (
        <>
          {/* KPI row */}
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 sm:gap-6 2xl:gap-8 mb-6 sm:mb-8">
            {KPIS.map((kpi) => <KpiCard key={kpi.label} kpi={kpi} />)}
          </div>

          {/* Charts row */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 2xl:gap-8">
            <ChartCard />
          </div>
        </>
      )}

      <AnimatePresence>
        {newLinkOpen && <NewLinkModal key="new-link" onClose={() => setNewLinkOpen(false)} />}
      </AnimatePresence>
    </motion.div>
  )
}
