// src/shared/ui/CardHeader.jsx
import { useTheme } from '@/shared/context/ThemeContext'

/**
 * CardHeader — Prism UI
 *
 * Encabezado estándar para cards internas: título + descripción a la izquierda,
 * slot de acción (Badge, Button, etc.) a la derecha. Incluye border-b.
 *
 * Props:
 *   title       node      — título del card (puede incluir íconos o elementos animados)
 *   description string?   — subtítulo muted bajo el título
 *   className   string?   — clases extra en el contenedor (e.g. padding override)
 *   children    node?     — slot derecho (Badge, Button, etc.)
 */
export default function CardHeader({ title, description, className = 'p-6', children }) {
  const { isDarkMode } = useTheme()

  return (
    <div className={`border-b flex justify-between items-center ${
      isDarkMode ? 'border-white/10' : 'border-black/5'
    } ${className}`}>
      <div>
        <h3 className={`font-bold text-lg tracking-tight flex items-center gap-2 ${isDarkMode ? 'text-white' : 'text-[#111113]'}`}>
          {title}
        </h3>
        {description && (
          <p className={`text-xs font-medium mt-1 ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
            {description}
          </p>
        )}
      </div>
      {children && <div className="flex-shrink-0">{children}</div>}
    </div>
  )
}

// app/components/ui/CardHeader.vue
<script setup>
import { useThemeStore } from '~/stores/theme'

defineProps({
  title: { type: String, default: '' },
  description: { type: String, default: '' },
  wrapperClass: { type: String, default: 'p-6' },
})

const themeStore = useThemeStore()
</script>

<template>
  <div :class="['border-b flex justify-between items-center', themeStore.isDarkMode ? 'border-white/10' : 'border-black/5', wrapperClass]">
    <div>
      <h3 :class="['font-bold text-lg tracking-tight flex items-center gap-2', themeStore.isDarkMode ? 'text-white' : 'text-[#111113]']">
        <slot name="title">{{ title }}</slot>
      </h3>
      <p v-if="description" :class="['text-xs font-medium mt-1', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
        {{ description }}
      </p>
    </div>
    <div v-if="$slots.default" class="shrink-0">
      <slot />
    </div>
  </div>
</template>
