// src/shared/ui/Modal.jsx
import { useEffect, useRef } from 'react'
import { X } from 'lucide-react'
import { motion } from 'framer-motion'
import { useTheme } from '@/shared/context/ThemeContext'
import useMediaQuery from '@/shared/hooks/useMediaQuery'
import Button from './Button'

/**
 * Modal — Prism UI
 *
 * Wrapper glass estándar para modales de formulario.
 * Los modales de recibo (ReceiptModal, WithdrawReceiptModal) usan AnimatePresence
 * y diseño especializado — no usan este componente.
 *
 * Props:
 *   onClose       fn        — handler de cierre (backdrop + X button + Escape key)
 *   title         string    — título del header (h2)
 *   description   node?     — subtítulo del header (puede ser JSX)
 *   icon          node?     — ícono junto al título (e.g. <ArrowUpFromLine />)
 *   maxWidth      string?   — ancho máximo del modal (default '480px')
 *   footer        node?     — contenido del footer (wrapped en barra con borde y fondo)
 *   className     string?   — clases extra en el contenedor interno (e.g. 'max-h-[90vh] flex flex-col')
 *   children      node      — cuerpo del modal
 */
export default function Modal({
  onClose,
  title,
  description,
  icon,
  maxWidth = '480px',
  footer,
  className = '',
  children,
}) {
  const { isDarkMode } = useTheme()
  const isMobile = !useMediaQuery('(min-width: 640px)')
  const containerRef = useRef(null)

  // Escape key handler
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [onClose])

  // Prevent body scroll while modal is open
  useEffect(() => {
    const original = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = original }
  }, [])

  // Focus trap: keep focus within modal (re-queries on each Tab press)
  useEffect(() => {
    const el = containerRef.current
    if (!el) return

    const getFocusable = () =>
      el.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')

    const initial = getFocusable()
    if (initial.length > 0) initial[0].focus()

    const handleTab = (e) => {
      if (e.key !== 'Tab') return
      const focusable = getFocusable()
      if (focusable.length === 0) return
      const first = focusable[0]
      const last = focusable[focusable.length - 1]
      if (e.shiftKey) {
        if (document.activeElement === first) { e.preventDefault(); last.focus() }
      } else {
        if (document.activeElement === last) { e.preventDefault(); first.focus() }
      }
    }
    document.addEventListener('keydown', handleTab)
    return () => document.removeEventListener('keydown', handleTab)
  }, [])

  return (
    <motion.div
      exit={{ opacity: 0 }}
      transition={{ duration: 0.15 }}
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center sm:p-4"
    >
      {/* Backdrop */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.15 }}
        className={`absolute inset-0 backdrop-blur-md backdrop-saturate-200 ${
          isDarkMode ? 'bg-black/70' : 'bg-[#111113]/40'
        }`}
        onClick={onClose}
      />

      {/* Container */}
      <motion.div
        ref={containerRef}
        {...(isMobile && {
          drag: 'y',
          dragConstraints: { top: 0 },
          dragElastic: 0.2,
          onDragEnd: (e, info) => {
            if (info.offset.y > 100 || info.velocity.y > 500) onClose()
          },
        })}
        initial={{ opacity: 0, scale: 0.95, y: 10 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 10 }}
        transition={{
          opacity: { duration: 0.15 },
          scale: { type: 'spring', stiffness: 400, damping: 30 },
          y: { type: 'spring', stiffness: 400, damping: 30 },
        }}
        role="dialog"
        aria-modal="true"
        aria-labelledby="modal-title"
        style={{ maxWidth }}
        className={`relative w-full rounded-t-[24px] sm:rounded-[24px] border overflow-hidden shadow-2xl max-h-[95vh] sm:max-h-[90vh] pb-[env(safe-area-inset-bottom)] sm:pb-0 ${
          isDarkMode
            ? 'bg-[#252429]/80 backdrop-blur-3xl border-white/20 border-t-white/30'
            : 'bg-white/90 backdrop-blur-3xl border-white shadow-[0_20px_60px_rgba(0,0,0,0.15)]'
        } ${className}`}
      >
        {/* Handle bar mobile */}
        <div className="sm:hidden flex justify-center pt-3 pb-1">
          <div className={`w-10 h-1 rounded-full ${isDarkMode ? 'bg-white/20' : 'bg-black/10'}`} />
        </div>

        {/* Header */}
        <div className={`px-5 sm:px-8 py-4 sm:py-6 border-b flex justify-between items-start flex-shrink-0 ${
          isDarkMode ? 'border-white/10' : 'border-black/5'
        }`}>
          <div>
            <h2 id="modal-title" className={`text-xl sm:text-2xl font-bold tracking-tight flex items-center gap-2 ${
              isDarkMode ? 'text-white' : 'text-[#111113]'
            }`}>
              {icon && <span className="text-[#7C3AED]">{icon}</span>}
              {title}
            </h2>
            {description && (
              <p className={`text-sm mt-1 font-medium ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`}>
                {description}
              </p>
            )}
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} className="!w-11 !h-11 sm:!w-10 sm:!h-10">
            <X size={20} />
          </Button>
        </div>

        {/* Body */}
        {children}

        {/* Footer */}
        {footer && (
          <div className={`px-5 sm:px-8 py-5 sm:py-6 flex gap-3 sm:gap-4 border-t flex-shrink-0 ${
            isDarkMode ? 'bg-[#111113]/40 border-white/10' : 'bg-gray-50/50 border-black/5'
          }`}>
            {footer}
          </div>
        )}
      </motion.div>
    </motion.div>
  )
}

// app/components/ui/Modal.vue
<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { motion } from 'motion-v'
import { X } from 'lucide-vue-next'
import { useThemeStore } from '~/stores/theme'
import { useMediaQuery } from '~/composables/useMediaQuery'
import { useScrollLock } from '~/composables/useScrollLock'
import { useChromeBlur } from '~/composables/useChromeBlur'
import { getModalGlass } from '~/utils/cardClasses'
import Button from './Button.vue'

const props = defineProps({
  title: { type: String, required: true },
  description: { type: String, default: '' },
  icon: { type: [Object, Function, null], default: null },
  maxWidth: { type: String, default: '480px' },
  wrapperClass: { type: String, default: '' },
})
const emit = defineEmits(['close'])

const themeStore = useThemeStore()
const isMobile = computed(() => !useMediaQuery('(min-width: 640px)').value)
const containerRef = ref(null)
let trigger = null

useScrollLock(true)
useChromeBlur(true)

const mobileInitial = { y: '100%' }
const mobileAnimate = { y: 0, transition: { type: 'spring', stiffness: 380, damping: 36 } }
const mobileExit = { y: '100%' }

const desktopInitial = { opacity: 0, scale: 0.95, y: 10 }
const desktopAnimate = {
  opacity: 1,
  scale: 1,
  y: 0,
  transition: {
    opacity: { duration: 0.15 },
    scale: { type: 'spring', stiffness: 400, damping: 30 },
    y: { type: 'spring', stiffness: 400, damping: 30 },
  },
}
const desktopExit = { opacity: 0, scale: 0.95, y: 10 }

const getContainerEl = () => containerRef.value?.$el ?? containerRef.value

const onKey = (e) => {
  if (e.key === 'Escape') emit('close')
  const el = getContainerEl()
  if (e.key !== 'Tab' || !el?.querySelectorAll) return
  const focusable = el.querySelectorAll(
    'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
  )
  if (focusable.length === 0) return
  const first = focusable[0]
  const last = focusable[focusable.length - 1]
  if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus() }
  else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus() }
}

onMounted(() => {
  if (typeof document === 'undefined') return
  trigger = document.activeElement
  document.addEventListener('keydown', onKey)
  const el = getContainerEl()
  const focusable = el?.querySelectorAll?.(
    'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
  )
  if (focusable && focusable.length > 0) focusable[0].focus()
})

onUnmounted(() => {
  if (typeof document === 'undefined') return
  document.removeEventListener('keydown', onKey)
  if (trigger && document.contains(trigger)) trigger.focus()
})

const onDragEnd = (_e, info) => {
  if (!isMobile.value) return
  if (info.offset.y > 100 || info.velocity.y > 500) {
    if (typeof document !== 'undefined') document.activeElement?.blur()
    emit('close')
  }
}

const modalClass = computed(() => getModalGlass(themeStore.isDarkMode))
</script>

<template>
  <ClientOnly>
    <Teleport to="body">
      <motion.div
        :exit="{ opacity: 0 }"
        :transition="{ duration: 0.15 }"
        class="fixed inset-0 z-50 flex items-end sm:items-center justify-center sm:p-4"
      >
        <motion.div
          :initial="{ opacity: 0 }"
          :animate="{ opacity: 1 }"
          :transition="{ duration: 0.15 }"
          :class="['absolute inset-0 backdrop-blur-md backdrop-saturate-200', themeStore.isDarkMode ? 'bg-black/70' : 'bg-[#111113]/40']"
          @click="emit('close')"
        />
        <motion.div
          ref="containerRef"
          :initial="isMobile ? mobileInitial : desktopInitial"
          :animate="isMobile ? mobileAnimate : desktopAnimate"
          :exit="isMobile ? mobileExit : desktopExit"
          :drag="isMobile ? 'y' : false"
          :drag-constraints="{ top: 0, bottom: 600 }"
          :drag-elastic="0.2"
          role="dialog"
          aria-modal="true"
          aria-labelledby="modal-title"
          :style="{ maxWidth }"
          :class="[
            'relative w-full flex flex-col rounded-t-[24px] sm:rounded-[24px] overflow-hidden max-h-[95vh] sm:max-h-[90vh] pb-[env(safe-area-inset-bottom)] sm:pb-0',
            modalClass,
            wrapperClass,
          ]"
          @drag-end="onDragEnd"
        >
          <div class="sm:hidden flex justify-center pt-3 pb-1 flex-shrink-0">
            <div :class="['w-10 h-1 rounded-full', themeStore.isDarkMode ? 'bg-white/20' : 'bg-black/10']" />
          </div>

          <div :class="['px-5 sm:px-8 py-4 sm:py-6 border-b flex justify-between items-start flex-shrink-0', themeStore.isDarkMode ? 'border-white/10' : 'border-black/5']">
            <div>
              <h2 id="modal-title" :class="['text-xl sm:text-2xl font-bold tracking-tight flex items-center gap-2', themeStore.isDarkMode ? 'text-white' : 'text-[#111113]']">
                <span v-if="icon" class="text-[#7C3AED]"><component :is="icon" :size="24" /></span>
                {{ title }}
              </h2>
              <p v-if="description" :class="['text-sm mt-1 font-medium', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']">
                {{ description }}
              </p>
            </div>
            <Button variant="ghost" size="icon" class="!w-11 !h-11 sm:!w-10 sm:!h-10" @click="emit('close')">
              <X :size="20" />
            </Button>
          </div>

          <div class="flex-1 overflow-y-auto min-h-0 flex flex-col">
            <slot />
          </div>

          <div
            v-if="$slots.footer"
            :class="['px-5 sm:px-8 py-5 sm:py-6 flex gap-3 sm:gap-4 border-t flex-shrink-0', themeStore.isDarkMode ? 'bg-[#111113]/40 border-white/10' : 'bg-gray-50/50 border-black/5']"
          >
            <slot name="footer" />
          </div>
        </motion.div>
      </motion.div>
    </Teleport>
  </ClientOnly>
</template>
