// src/shared/ui/SearchInput.jsx
import { Search } from 'lucide-react'
import { useTheme } from '@/shared/context/ThemeContext'

/**
 * SearchInput — input de búsqueda con estilo glass Prism UI.
 *
 * Props:
 *   value        string   — valor controlado
 *   onChange     fn       — handler (e) => void
 *   placeholder  string   — texto de placeholder
 *   className    string   — clases extra para el contenedor (ej: "w-72", "w-48")
 */
export default function SearchInput({ value, onChange, placeholder = 'Buscar...', className = 'w-72' }) {
  const { isDarkMode } = useTheme()

  return (
    <div className={`flex items-center px-4 py-2 rounded-xl transition-all ${
      isDarkMode
        ? 'bg-[#111113]/50 border border-white/5 focus-within:border-[#7C3AED]/40'
        : 'bg-white/60 border border-white focus-within:border-[#7C3AED]/30'
    } ${className}`}>
      <Search size={14} className={`flex-shrink-0 ${isDarkMode ? 'text-[#888991]' : 'text-[#67656E]'}`} />
      <input
        type="text"
        placeholder={placeholder}
        value={value}
        onChange={onChange}
        aria-label={placeholder.replace('...', '').trim()}
        className={`bg-transparent border-none outline-none text-xs ml-2 w-full font-medium ${
          isDarkMode ? 'text-[#D8D7D9] placeholder:text-[#888991]' : 'text-[#111113] placeholder:text-[#B0AFB4]'
        }`}
      />
    </div>
  )
}

// app/components/ui/SearchInput.vue
<script setup>
import { computed } from 'vue'
import { Search } from 'lucide-vue-next'
import { useThemeStore } from '~/stores/theme'

const props = defineProps({
  modelValue: { type: String, default: '' },
  placeholder: { type: String, default: 'Buscar...' },
  wrapperClass: { type: String, default: 'w-full sm:w-72' },
})
const emit = defineEmits(['update:modelValue'])

const themeStore = useThemeStore()

const containerClass = computed(() =>
  themeStore.isDarkMode
    ? 'bg-[#111113]/50 border border-white/5 focus-within:border-[#7C3AED]/40'
    : 'bg-white/60 border border-white focus-within:border-[#7C3AED]/30',
)

const inputClass = computed(() =>
  themeStore.isDarkMode
    ? 'text-[#D8D7D9] placeholder:text-[#888991]'
    : 'text-[#111113] placeholder:text-[#B0AFB4]',
)

const ariaLabel = computed(() => props.placeholder.replace('...', '').trim())
</script>

<template>
  <div :class="['flex items-center px-4 py-2 rounded-xl transition-all', containerClass, wrapperClass]">
    <Search :size="14" :class="['flex-shrink-0', themeStore.isDarkMode ? 'text-[#888991]' : 'text-[#67656E]']" />
    <input
      type="text"
      :placeholder="placeholder"
      :value="modelValue"
      :aria-label="ariaLabel"
      :class="['bg-transparent border-none outline-none text-xs ml-2 w-full font-medium', inputClass]"
      @input="emit('update:modelValue', $event.target.value)"
    />
  </div>
</template>
